[theme]
primaryColor = "#6366F1"
backgroundColor = "#0B1120"
secondaryBackgroundColor = "#0f1420"
textColor = "#E2E8F0"
font = "sans serif"
 
[client]
showErrorDetails = false
toolbarMode = "minimal"
 
[logger]
level = "error"
 
[server]
maxUploadSize = 200
enableXsrfProtection = true